/* Banco inicial; atualizado pelo GitHub Actions. */
window.CONCURSOS = [
  {
    "id": "alepa-medio-2026",
    "name": "ALEPA — Concurso Público 001/2026 (Nível Médio)",
    "shortName": "ALEPA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "aberto",
    "monitorMode": "date",
    "editalDate": "2026-09-28",
    "registrationStart": "2026-10-01",
    "registrationEnd": "2026-11-04",
    "vacancies": "17",
    "education": "Nível médio",
    "bank": "Fundação CETAP",
    "sourceUrl": "https://www.alepa.pa.gov.br/Transparencia/Page/Concursos",
    "confidence": "Oficial",
    "sourceType": "oficial"
  },
  {
    "id": "alepa-superior-2026",
    "name": "ALEPA — Concurso Público 002/2026 (Superior)",
    "shortName": "ALEPA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "aberto",
    "monitorMode": "date",
    "editalDate": "2026-09-28",
    "registrationStart": "2026-10-01",
    "registrationEnd": "2026-11-04",
    "vacancies": "113",
    "education": "Nível superior",
    "bank": "Fundação CETAP",
    "sourceUrl": "https://www.alepa.pa.gov.br/Transparencia/Page/Concursos",
    "confidence": "Oficial",
    "sourceType": "oficial"
  },
  {
    "id": "alepa-procurador-2026",
    "name": "ALEPA — Concurso Público 003/2026 (Procurador)",
    "shortName": "ALEPA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "aberto",
    "monitorMode": "date",
    "editalDate": "2026-09-28",
    "registrationStart": "2026-10-01",
    "registrationEnd": "2026-11-04",
    "vacancies": "5",
    "education": "Superior completo",
    "bank": "Fundação CETAP",
    "sourceUrl": "https://www.alepa.pa.gov.br/Transparencia/Page/Concursos",
    "confidence": "Oficial",
    "sourceType": "oficial"
  },
  {
    "id": "trt8-2026",
    "name": "TRT da 8ª Região — Concurso 2026",
    "shortName": "TRT8",
    "uf": "PA",
    "city": "Belém",
    "scope": "regional",
    "status": "aberto",
    "monitorMode": "date",
    "editalDate": "2026-09-30",
    "registrationStart": "2026-10-05",
    "registrationEnd": "2026-11-05",
    "vacancies": "Cadastro de reserva",
    "education": "Nível superior",
    "bank": "Fundação Carlos Chagas (FCC)",
    "sourceUrl": "https://www.trt8.jus.br/",
    "confidence": "Edital publicado",
    "sourceType": "oficial",
    "notes": "Abrange Pará e Amapá. As provas estão previstas para janeiro de 2027."
  },
  {
    "id": "ifpa-2026",
    "name": "IFPA — Técnico-Administrativos 2026",
    "shortName": "IFPA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "aberto",
    "monitorMode": "date",
    "editalDate": "2026-09-18",
    "registrationStart": "2026-09-21",
    "registrationEnd": "2026-10-20",
    "vacancies": "65",
    "education": "Médio, técnico e superior",
    "bank": "Instituto AOCP",
    "sourceUrl": "https://www.ifpa.edu.br/",
    "confidence": "Edital publicado",
    "sourceType": "oficial"
  },
  {
    "id": "seduc-pa-2026",
    "name": "SEDUC PA — Concurso 2026",
    "shortName": "SEDUC PA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "aberto",
    "monitorMode": "date",
    "editalDate": "2026-08-28",
    "registrationStart": "2026-08-31",
    "registrationEnd": "2026-10-07",
    "vacancies": "2.000",
    "education": "Médio e superior",
    "bank": "FGV",
    "sourceUrl": "https://www.seduc.pa.gov.br/",
    "confidence": "Edital publicado",
    "sourceType": "oficial"
  },
  {
    "id": "fhcgv-2026",
    "name": "Hospital de Clínicas Gaspar Vianna — Concurso 2026",
    "shortName": "FHCGV",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "aberto",
    "monitorMode": "official",
    "vacancies": "215 + CR",
    "education": "Médio, técnico e superior",
    "bank": "Consulplan",
    "sourceUrl": "https://www.gasparvianna.pa.gov.br/",
    "confidence": "Edital publicado",
    "sourceType": "oficial"
  },
  {
    "id": "pc-pa-2026-27",
    "name": "Polícia Civil do Pará — novo concurso",
    "shortName": "PC PA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "237 (referência publicada)",
    "education": "Médio e superior",
    "bank": "A definir",
    "sourceUrl": "https://www.pc.pa.gov.br/",
    "confidence": "Previsão/movimentação",
    "sourceType": "previsao",
    "notes": "O portal só mudará para ABERTO após encontrar confirmação oficial do edital e do período de inscrição."
  },
  {
    "id": "agtran-pa-2026",
    "name": "AGTRAN PA — Agência de Transporte Metropolitano",
    "shortName": "AGTRAN PA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "67 (referência mínima)",
    "education": "Médio, técnico e superior",
    "bank": "Fundação CETAP",
    "sourceUrl": "https://www.agtran.pa.gov.br/",
    "confidence": "Banca definida",
    "sourceType": "previsao"
  },
  {
    "id": "iterpa-2026",
    "name": "ITERPA — Instituto de Terras do Pará",
    "shortName": "ITERPA",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "112 + CR",
    "education": "Todos os níveis",
    "bank": "Instituto AOCP",
    "sourceUrl": "https://www.iterpa.pa.gov.br/",
    "confidence": "Banca contratada",
    "sourceType": "previsao"
  },
  {
    "id": "imetropara-2026",
    "name": "IMETROPARÁ — novo concurso",
    "shortName": "IMETROPARÁ",
    "uf": "PA",
    "city": "Belém",
    "scope": "estadual",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "66",
    "education": "Médio e superior",
    "bank": "Fundação CETAP",
    "sourceUrl": "https://www.imetropara.pa.gov.br/",
    "confidence": "Banca definida",
    "sourceType": "previsao"
  },
  {
    "id": "gmb-belem",
    "name": "Guarda Municipal de Belém",
    "shortName": "GMB",
    "uf": "PA",
    "city": "Belém",
    "scope": "municipal",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "A confirmar",
    "education": "A confirmar",
    "bank": "A definir",
    "sourceUrl": "https://www.belem.pa.gov.br/",
    "confidence": "Acompanhamento",
    "sourceType": "previsao",
    "notes": "A situação será elevada somente com confirmação oficial."
  },
  {
    "id": "semmma-belem-2026",
    "name": "SEMMA Belém — possível novo concurso",
    "shortName": "SEMMA",
    "uf": "PA",
    "city": "Belém",
    "scope": "municipal",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "A definir",
    "education": "A definir",
    "bank": "A definir",
    "sourceUrl": "https://www.belem.pa.gov.br/",
    "confidence": "Comissão/levantamento",
    "sourceType": "previsao"
  },
  {
    "id": "prf-2027",
    "name": "Polícia Rodoviária Federal — novo concurso",
    "shortName": "PRF",
    "uf": "",
    "city": "",
    "scope": "nacional",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "A confirmar",
    "education": "Conforme edital",
    "bank": "A definir",
    "sourceUrl": "https://www.gov.br/prf/pt-br",
    "confidence": "Pedido de autorização",
    "sourceType": "previsao",
    "notes": "Pedido de autorização não equivale a edital publicado."
  },
  {
    "id": "pf-2027",
    "name": "Polícia Federal — novo concurso",
    "shortName": "PF",
    "uf": "",
    "city": "",
    "scope": "nacional",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "A confirmar",
    "education": "Conforme edital",
    "bank": "A definir",
    "sourceUrl": "https://www.gov.br/pf/pt-br",
    "confidence": "Planejamento",
    "sourceType": "previsao",
    "notes": "O status permanecerá iminente até confirmação oficial."
  },
  {
    "id": "pec-pf-2026",
    "name": "Polícia Federal — Plano Especial de Cargos",
    "shortName": "PEC-PF",
    "uf": "",
    "city": "",
    "scope": "nacional",
    "status": "iminente",
    "monitorMode": "official",
    "vacancies": "192 autorizadas",
    "education": "Conforme edital",
    "bank": "A definir",
    "sourceUrl": "https://www.gov.br/pf/pt-br",
    "confidence": "Autorizado",
    "sourceType": "previsao"
  }
];
window.APP_CONFIG = {
  "lastDataUpdate": "2026-10-05",
  "automaticMonitorReady": true,
  "monitorInterval": "6h",
  "projectVersion": "2.0.0"
};
