(function(){
const data=window.CONCURSOS||[]; const today=new Date();
function calc(x){if(x.inicio&&x.fim){let a=new Date(x.inicio+'T00:00:00'),b=new Date(x.fim+'T23:59:59');if(today>=a&&today<=b)return'aberto';if(today>b)return'fechado';}return x.status||'iminente'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function label(s){return s==='aberto'?'ABERTO':s==='fechado'?'FECHADO':'IMINENTE'}
function card(x){let s=calc(x);return `<article class="card"><div class="card-top"><span class="badge ${s}">${label(s)}</span><span>${esc(x.uf==='Nacional'?'NACIONAL':x.uf)}</span></div><h3>${esc(x.nome)}</h3><p class="org">${esc(x.orgao||'')}</p><div class="meta"><span>📍 ${esc(x.municipio||'Nacional')}</span><span>🎓 ${esc(x.escolaridade||'A confirmar')}</span><span>📄 ${esc(x.vagas??'A confirmar')} vagas</span></div><div class="card-foot"><span>${esc(x.banca||'Banca a definir')}</span><a href="concurso.html?id=${encodeURIComponent(x.id)}">Detalhes →</a></div></article>`}
function qs(id){return document.getElementById(id)}
function init(){if(qs('year'))qs('year').textContent=today.getFullYear();let statuses=data.map(calc);if(qs('openCount')){qs('openCount').textContent=statuses.filter(x=>x==='aberto').length;qs('soonCount').textContent=statuses.filter(x=>x==='iminente').length;qs('closedCount').textContent=statuses.filter(x=>x==='fechado').length;qs('totalCount').textContent=data.length;qs('featured').innerHTML=data.filter(x=>calc(x)!=='fechado').slice(0,6).map(card).join('')}
if(qs('list'))setupList(); if(qs('detail'))setupDetail(); document.querySelector('.hamb')?.addEventListener('click',()=>document.querySelector('nav')?.classList.toggle('show'))}
function setupList(){let uf=qs('uf'),city=qs('city');[...new Set(data.map(x=>x.uf).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).forEach(v=>uf.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`));function cities(){let u=uf.value;let cs=[...new Set(data.filter(x=>!u||x.uf===u).map(x=>x.municipio).filter(Boolean))].sort((a,b)=>a.localeCompare(b));city.innerHTML='<option value="">Todos</option>'+cs.map(v=>`<option>${esc(v)}</option>`).join('')}cities();uf.addEventListener('change',()=>{cities();render()});['q','city','scope','status','level'].forEach(id=>qs(id).addEventListener('input',render));qs('clear').onclick=()=>{['q','uf','city','scope','status','level'].forEach(id=>qs(id).value='');cities();render()};function render(){let q=qs('q').value.toLowerCase().trim(),u=uf.value,c=city.value,sc=qs('scope').value,st=qs('status').value,l=qs('level').value;let out=data.filter(x=>{let s=calc(x),txt=[x.nome,x.orgao,x.banca,x.municipio,x.uf].join(' ').toLowerCase();return(!q||txt.includes(q))&&(!u||x.uf===u)&&(!c||x.municipio===c)&&(!sc||x.abrangencia===sc)&&(!st||s===st)&&(!l||String(x.escolaridade||'').includes(l))});qs('resultCount').textContent=`${out.length} concurso${out.length===1?'':'s'}`;qs('list').innerHTML=out.map(card).join('')||'<div class="empty">Nenhum concurso encontrado.</div>'}render()}
function setupDetail(){let id=new URLSearchParams(location.search).get('id'),x=data.find(a=>a.id===id)||data[0];if(!x){qs('detail').innerHTML='<div class="empty">Concurso não encontrado.</div>';return}let s=calc(x);qs('detail').innerHTML=`<a class="back" href="concursos.html">← Voltar</a><div class="detail-head"><div><span class="badge ${s}">${label(s)}</span><h1>${esc(x.nome)}</h1><p>${esc(x.orgao)}</p></div><div class="detail-box"><b>${esc(x.vagas??'A confirmar')}</b><span>vagas / CR</span></div></div><div class="detail-grid"><section class="panel"><h2>Informações</h2><dl><dt>Local</dt><dd>${esc(x.municipio||'Nacional')}${x.uf&&x.uf!=='Nacional'?' — '+esc(x.uf):''}</dd><dt>Abrangência</dt><dd>${esc(x.abrangencia)}</dd><dt>Escolaridade</dt><dd>${esc(x.escolaridade||'A confirmar')}</dd><dt>Banca</dt><dd>${esc(x.banca||'A definir')}</dd><dt>Última atualização</dt><dd>${esc(x.updated||'—')}</dd></dl></section><section class="panel"><h2>Inscrições</h2><p><b>Início:</b> ${esc(x.inicio||'A confirmar')}</p><p><b>Fim:</b> ${esc(x.fim||'A confirmar')}</p><p><b>Prova:</b> ${esc(x.prova||'A confirmar')}</p><a class="btn primary" target="_blank" rel="noopener" href="${esc(x.fonte||'#')}">Fonte oficial / referência</a></section></div>`}
init();})();
