import {requireAdmin} from './_auth.js';
function norm(x){return {...x,id:String(x.id||crypto.randomUUID()),nome:String(x.nome||'').trim(),orgao:String(x.orgao||''),uf:String(x.uf||''),municipio:String(x.municipio||''),abrangencia:String(x.abrangencia||'Municipal'),status:String(x.status||'iminente'),vagas:String(x.vagas??''),escolaridade:String(x.escolaridade||''),banca:String(x.banca||''),inicio:x.inicio||null,fim:x.fim||null,prova:x.prova||null,fonte:String(x.fonte||''),oficial:x.oficial?1:0,origem:String(x.origem||'manual'),confidence:String(x.confidence||'manual')};}
export async function onRequestPost({request,env}){
 const denied=await requireAdmin(request,env);if(denied)return denied;if(!env.DB)return new Response(JSON.stringify({error:'D1 não configurado.'}),{status:503,headers:{'content-type':'application/json'}});
 const x=norm(await request.json());if(!x.nome||!x.uf)return new Response(JSON.stringify({error:'Nome e UF são obrigatórios.'}),{status:400,headers:{'content-type':'application/json'}});const now=new Date().toISOString();
 await env.DB.prepare(`INSERT INTO contests (id,nome,orgao,uf,municipio,abrangencia,status,vagas,escolaridade,banca,inicio,fim,prova,fonte,oficial,origem,confidence,updated,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET nome=excluded.nome,orgao=excluded.orgao,uf=excluded.uf,municipio=excluded.municipio,abrangencia=excluded.abrangencia,status=excluded.status,vagas=excluded.vagas,escolaridade=excluded.escolaridade,banca=excluded.banca,inicio=excluded.inicio,fim=excluded.fim,prova=excluded.prova,fonte=excluded.fonte,oficial=excluded.oficial,origem=excluded.origem,confidence=excluded.confidence,updated=excluded.updated,updated_at=excluded.updated_at`).bind(x.id,x.nome,x.orgao,x.uf,x.municipio,x.abrangencia,x.status,x.vagas,x.escolaridade,x.banca,x.inicio,x.fim,x.prova,x.fonte,x.oficial,x.origem,x.confidence,now,now,now).run();
 await env.DB.prepare('INSERT INTO history (contest_id,action,details,created_at) VALUES (?,?,?,?)').bind(x.id,'save',x.nome,now).run(); return new Response(JSON.stringify({ok:true,id:x.id}),{headers:{'content-type':'application/json'}});
}
export async function onRequestDelete({request,env}){
 const denied=await requireAdmin(request,env);if(denied)return denied;if(!env.DB)return new Response(JSON.stringify({error:'D1 não configurado.'}),{status:503,headers:{'content-type':'application/json'}});const id=new URL(request.url).searchParams.get('id');if(!id)return new Response(JSON.stringify({error:'ID obrigatório'}),{status:400,headers:{'content-type':'application/json'}});const now=new Date().toISOString();await env.DB.prepare('DELETE FROM contests WHERE id=?').bind(id).run();await env.DB.prepare('INSERT INTO history (contest_id,action,details,created_at) VALUES (?,?,?,?)').bind(id,'delete',id,now).run();return new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json'}});
}
